"""Add linkedin_url, supervisor, category to clubs and seed 28 student organizations

Revision ID: 020
Revises: 019
Create Date: 2026-04-12

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020"
down_revision: Union[str, None] = "019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("clubs", sa.Column("linkedin_url", sa.String(500), nullable=True))
    op.add_column("clubs", sa.Column("supervisor", sa.String(300), nullable=True))
    op.add_column("clubs", sa.Column("category", sa.String(100), nullable=True))

    clubs_table = sa.table(
        "clubs",
        sa.column("name", sa.String),
        sa.column("login", sa.String),
        sa.column("password", sa.String),
        sa.column("role", sa.String),
        sa.column("type", sa.String),
        sa.column("logo_url", sa.String),
        sa.column("description", sa.Text),
        sa.column("email", sa.String),
        sa.column("facebook_url", sa.String),
        sa.column("instagram_url", sa.String),
        sa.column("website_url", sa.String),
        sa.column("linkedin_url", sa.String),
        sa.column("supervisor", sa.String),
        sa.column("category", sa.String),
    )

    # bcrypt hash of "kozminski2026" - placeholder password for all clubs
    placeholder_pwd = "$2b$12$LJ3m4ys4Gz1GzH0oXQ5KxuFmQr4iE6YP6BVzFbNjMh5TCbXvkzjnO"

    clubs = [
        {
            "name": "Women in Organisation",
            "login": "women_in_org",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Studenckie Koło Naukowe Women in Organisations powstało z potrzeby wspierania młodych kobiet wchodzących na rynek pracy. Wierzymy, że każda młoda kobieta ma w sobie potencjał pozwalający osiągnąć sukces. Koło organizuje warsztaty, szkolenia, wykłady i spotkania z profesjonalistami z różnych branż.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/w.in_.org_.png",
            "supervisor": "Dr Anna Górska",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/skn_wio/",
            "facebook_url": "https://www.facebook.com/SKN-Women-in-Organizations-100954501812683",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skn-women-in-organisations/",
        },
        {
            "name": "Kozminski Business Club",
            "login": "kozminski_business_club",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Łączy czołowych polskich praktyków biznesu ze studentami, zwiększając ich świadomość biznesową i zawodową. Działa na dwóch filarach: łączenie przedsiębiorców ze studentami oraz organizacja wydarzeń promujących przedsiębiorczość i rozwój kariery.",
            "logo_url": None,
            "supervisor": "Dr Marta Połeć",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kozminski_business_club/",
            "facebook_url": "https://www.facebook.com/KozminskiBusinessClub",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/kozminski-business-club/",
        },
        {
            "name": "Koło Przedsiębiorczości SUKCES",
            "login": "kolo_sukces",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Realizuje inicjatywy przedsiębiorcze wśród członków, rozwijając wiedzę z retoryki, interdyscyplinarnego rozwiązywania problemów, marketingu i komunikacji. Składa się z trzech sekcji: Kozminski Debate Academy, Students of Kozminski oraz Sekcja Kosmiczna.",
            "logo_url": None,
            "supervisor": "Dr Agnieszka Padzik-Wołos",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kozminski.debate.academy",
            "facebook_url": "https://www.facebook.com/profile.php?id=100094067446253",
            "website_url": "https://linktr.ee/studentsofkozminski",
            "linkedin_url": None,
        },
        {
            "name": "SKN PSYCHONOMIA",
            "login": "skn_psychonomia",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Koło Naukowe Psychologii Społeczno-Ekonomicznej PSYCHONOMIA łączy studentów zainteresowanych tym, jak zasady i mechanizmy psychologiczne wyjaśniają zachowania ekonomiczne. Członkowie badają wpływ przetwarzania informacji, procesów emocjonalnych i motywacyjnych na decyzje konsumenckie i zawodowe.",
            "logo_url": None,
            "supervisor": "Dr Anna Macko",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/SKN-Psychonomia-109199584580156",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/sknpsychonomia/",
        },
        {
            "name": "NextGen.PM Kozminski Club",
            "login": "nextgen_pm",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Studenckie koło naukowe skupiające się na zarządzaniu projektami. Przekształca wiedzę teoretyczną w praktykę poprzez projekty uniwersyteckie i inicjatywy członków, współpracuje z firmami zewnętrznymi, organizuje szkolenia i warsztaty.",
            "logo_url": None,
            "supervisor": "mgr Marcin Opas",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/nextgen.pm/",
            "facebook_url": None,
            "website_url": "https://www.nextgen.pm/",
            "linkedin_url": "https://www.linkedin.com/company/94837743/",
        },
        {
            "name": "Culture Club",
            "login": "culture_club",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Miejsce, gdzie pasja do kultury i sztuki łączy się z przedsiębiorczością. Członkowie tworzą i eksplorują sztukę, rozwijając jednocześnie umiejętności biznesowe poprzez wydarzenia, wystawy, warsztaty i networking.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/Culture-Club-logo-horizontal2-100px.png",
            "supervisor": "Dr Piotr Pilch, Dr Krzysztof Kuźmicz",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/skn_culture_club/",
            "facebook_url": "https://www.facebook.com/profile.php?id=100092804348565",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skn-culture-club/",
        },
        {
            "name": "SKN Tiger",
            "login": "skn_tiger",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Koło z najdłuższą tradycją w Akademii Leona Koźmińskiego, od początku tworzone przez studentów dla studentów. Skupia się na ekonomii, polityce i społeczeństwie, organizuje prezentacje i wydarzenia prowadzone przez członków i ekspertów zewnętrznych oraz cykliczne debaty na kontrowersyjne tematy.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/573519780_1361379349011907_6390402108358994649_n.jpg",
            "supervisor": "mgr Serhii Druchyn",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/skn.tiger/",
            "facebook_url": "https://www.facebook.com/SKNTiger",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skntiger/",
        },
        {
            "name": "@Kozminski_AI",
            "login": "kozminski_ai",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Skupia się na programowaniu, sztucznej inteligencji i data science w biznesie. Rozwija kompetencje poprzez kursy, szkolenia i wspólne projekty z analizy danych, programowania i algorytmów. Współpracuje z firmami technologicznymi nad projektami AI w dziedzinach Computer Vision, NLP, modeli predykcyjnych i Reinforcement Learning.",
            "logo_url": None,
            "supervisor": "Dr Leon Ciechanowski",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kozminski_ai_club/",
            "facebook_url": "https://www.facebook.com/kozminski.ai.club",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/kozminski-ai-club/",
        },
        {
            "name": "SKN Kreatywni Society",
            "login": "skn_kreatywni",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Zarządzanie",
            "description": "Elitarna studencka organizacja marketingowa skupiona na kreatywnej synergii, tworzeniu treści, organizacji wydarzeń i zarządzaniu projektami. Członkowie zdobywają wiedzę marketingową, budują portfolio zawodowe i rozwijają kontakty kariery.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/kreat.png",
            "supervisor": "Dr Chrystyna Misiewicz, Dr Ewa Kiczmachowska",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kreatywni_society/",
            "facebook_url": "https://www.facebook.com/sknkreatywnisociety",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skn-kreatywni-society/about/",
        },
        {
            "name": "SKN Financial Markets Club",
            "login": "skn_fmc",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Finanse i Ekonomia",
            "description": "Koło angażuje się w analizę finansową, wyceny spółek, organizację wydarzeń, zarządzanie mediami społecznościowymi, inicjatywy charytatywne, pisanie o finansach i networking z profesjonalistami z branży.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/11db390a-5f5f-4abe-ad20-95f1d20c43f7.png",
            "supervisor": "Dr hab. Paweł Mielcarz",
            "email": None,
            "instagram_url": None,
            "facebook_url": None,
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "Data Science for Business",
            "login": "dsb_kozminski",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Finanse i Ekonomia",
            "description": "Przestrzeń dla studentów, którzy chcą rozwijać umiejętności analizy danych w finansach, marketingu, makroekonomii i ekonometrii. Motto: 'From data to decision – building a better world'. Łączy teorię z praktycznym zastosowaniem nowoczesnych narzędzi analitycznych.",
            "logo_url": None,
            "supervisor": "Dr Jakub Rybacki, mgr Sergiej Druczin",
            "email": None,
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/DSBKozminski",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "SKN Rachunkowości Finansowej AUDYTOR",
            "login": "skn_audytor",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Finanse i Ekonomia",
            "description": "Koło skupia się na poszerzaniu wiedzy z zakresu polskiej i międzynarodowej rachunkowości, podatków i audytu. Organizuje debaty na temat wyzwań rachunkowych i ewolucji sprawozdawczości finansowej.",
            "logo_url": None,
            "supervisor": "Dr Wojciech Strzelczyk, Dr Grygorii Kravchenko",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/alkkolonaukoweaudytor/",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skn-audytor/",
        },
        {
            "name": "Kozminski Consulting Club",
            "login": "kcc_kozminski",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Finanse i Ekonomia",
            "description": "Stowarzyszenie studenckie przygotowujące członków do kariery w konsultingu poprzez trzy filary: mentoring, rozwój umiejętności (szkolenia i warsztaty case-interview) oraz networking z dużymi firmami konsultingowymi. Działa w języku angielskim.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%20%D0%B1%D0%B5%D0%B7%20%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%20%288%29.png",
            "supervisor": "Dr Franjo Mlinarič",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kozminski_consulting_club/",
            "facebook_url": "https://www.facebook.com/profile.php?id=100089594051244",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/kozminski-consulting-club/",
        },
        {
            "name": "Koło Prawa Bankowego i Bankowości",
            "login": "kolo_bankowe",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Finanse i Ekonomia",
            "description": "Głównym celem jest pogłębienie zainteresowań studentów z zakresu bankowości oraz prawnych aspektów działań systemów bankowych poprzez projekty interdyscyplinarne.",
            "logo_url": None,
            "supervisor": "Prof. dr hab. Wojciech Góralczyk",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/profile.php?id=100080613336672",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skn-prawa-bankowego-i-bankowo%C5%9Bci/",
        },
        {
            "name": "SKN Inwestycji KAPITALNI",
            "login": "skn_kapitalni",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Finanse i Ekonomia",
            "description": "Umożliwia członkom rozwijanie i pogłębianie wiedzy z zakresu funkcjonowania rynków finansowych, pomaga podnosić świadomość inwestycyjną oraz umożliwia wymianę doświadczeń inwestycyjnych.",
            "logo_url": None,
            "supervisor": "Prof. dr hab. Adam Noga",
            "email": None,
            "instagram_url": "https://www.instagram.com/skn_kapitalni/",
            "facebook_url": "https://www.facebook.com/profile.php?id=100089306716305",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "Koło Naukowe Prawa Konstytucyjnego i Praw Człowieka \"Pro Libertate\"",
            "login": "pro_libertate",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Koło skupione na prawie konstytucyjnym, ustroju państwa, prawach obywatelskich i ochronie praw człowieka. Członkowie angażują się w dzielenie się wiedzą, dyskusje merytoryczne, spotkania z autorytetami prawnymi i wizyty w ważnych instytucjach państwowych.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/Pro%20Libertate-Blk-horizontal.png",
            "supervisor": "Prof. ALK dr hab. Michał Kowalski",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": None,
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "LEX MEDICINAE",
            "login": "lex_medicinae",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Koło Naukowe Prawa Medycznego i Farmaceutycznego, którego zakres działalności obejmuje pracę naukową i badawczą dot. przede wszystkim prawa medycznego oraz spraw pokrewnych. Popularyzuje wiedzę poprzez regularne spotkania, warsztaty, konferencje, sesje naukowe i szkolenia.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/360083903_782573756902086_4463837742984489386_n.png",
            "supervisor": "Dr Dariusz Hajdukiewicz",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/LexMedicinae",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "Koło Naukowe Prawa Karnego Crimen et Poena",
            "login": "crimen_et_poena",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Zajmuje się tematyką prawa i postępowania karnego, kryminalistyki, kryminologii oraz penitencjarystyki. Organizuje spotkania, wyjazdy, wykłady oraz szkolenia.",
            "logo_url": None,
            "supervisor": "Dr Michał Hudzik",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/KNPKALK/",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "Koło Naukowe Prawa Sportowego \"Societas Iuris Sportivi\"",
            "login": "societas_sportivi",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Łączy studentów zainteresowanych prawem sportowym i jego praktycznym zastosowaniem. Członkowie analizują polskie i międzynarodowe regulacje prawa sportowego, badają funkcjonowanie instytucji sportowych i organizują spotkania z ekspertami.",
            "logo_url": None,
            "supervisor": "Dr Dawid Kostecki",
            "email": None,
            "instagram_url": "https://www.instagram.com/alkknps/",
            "facebook_url": "https://www.facebook.com/alkknps",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "SKN Prawa Własności Intelektualnej ACTIO EFFICIENS",
            "login": "actio_efficiens",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Celem jest poszerzanie świadomości studentów z zakresu prawa własności intelektualnej poprzez dyskusje i prezentacje. Przyjmuje studentów wszystkich poziomów wiedzy, kierunków i lat studiów.",
            "logo_url": None,
            "supervisor": "Dr Joanna Buchalska",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/Actio-Efficiens-Prawnicze-Ko%C5%82o-Naukowe-Prawa-W%C5%82asno%C5%9Bci-Intelektualnej-185947314760404/",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "SKN Kozminski Energy",
            "login": "kozminski_energy",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Przestrzeń dla studentów zainteresowanych szeroko pojętym sektorem energetycznym, jego regulacjami prawnymi oraz wpływem transformacji energetycznej na gospodarkę i środowisko. Organizuje konferencje, warsztaty i spotkania z ekspertami.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/Ko%C5%82o%20NAUKOWE%20prawa%20ENERGETYCZNEGO_2.jpg",
            "supervisor": "Dr Aleksandra Knap",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": None,
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "Studenckie Koło Naukowe EX ANTE",
            "login": "skn_ex_ante",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Koło zajmujące się analizą ryzyk prawnych i gospodarczych oraz wpływu regulacji i wydarzeń międzynarodowych na decyzje biznesowe. Organizuje seminaria z ekspertami i wewnętrzne dyskusje analizujące przykłady rynkowe.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/Ex%20Ante%20logo.png",
            "supervisor": "Dr Maria Tomaszewska",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/skn.exante/",
            "facebook_url": "https://www.facebook.com/Ex-Ante-100882768509765/",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/studenckie-ko%C5%82o-naukowe-ex-ante/",
        },
        {
            "name": "SKN Prawa Handlowego IUS MERCATORUM",
            "login": "ius_mercatorum",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Eksploruje świat korporacji, mechanizmów rynkowych i praktycznego zastosowania przepisów prawa handlowego. Członkowie analizują kodeksy prawa korporacyjnego w kontekstach rzeczywistych, rozwiązują sprawy prawne i zapraszają praktyków.",
            "logo_url": None,
            "supervisor": "Prof. ALK dr hab. Konrad Zacharzewski",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kn_ius_mercatorum/",
            "facebook_url": "https://www.facebook.com/61556763634952/",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/ko%C5%82o-naukowe-prawa-handlowego-ius-mercatorum/",
        },
        {
            "name": "SKN FORUM (Kozminski Students Association)",
            "login": "skn_forum",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Skupia studentów prawa chcących rozwijać wiedzę i umiejętności praktyczne. Ułatwia networking z profesjonalistami prawnymi, organizuje wizyty instytucjonalne, obserwacje rozpraw sądowych i działalność badawczą.",
            "logo_url": None,
            "supervisor": "Dr Ben Sassi",
            "email": "[email protected]",
            "instagram_url": "https://instagram.com/kozminski_forum",
            "facebook_url": "https://www.facebook.com/FORUM.KLSA",
            "website_url": None,
            "linkedin_url": None,
        },
        {
            "name": "SKN Prawa Międzynarodowego Publicznego i Prawa UE \"Unitas\"",
            "login": "skn_unitas",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Prawo",
            "description": "Przestrzeń dla studentów zainteresowanych prawem międzynarodowym publicznym, prawem Unii Europejskiej oraz relacjami między państwami i organizacjami międzynarodowymi. Promuje współpracę międzynarodową, pogłębia wiedzę o ochronie praw człowieka i instytucjach UE.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/unitas_png.png",
            "supervisor": "Dr Anna Pudło-Jaremek",
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/sknunitas",
            "facebook_url": None,
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/skn-prawa-mi%C4%99dzynarodowego-publicznego-i-prawa-ue-unitas/",
        },
        {
            "name": "Kozminski International Society",
            "login": "kis_kozminski",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Organizacje Studenckie",
            "description": "\"Students helping students\" – organizacja pomagająca i reprezentująca studentów międzynarodowych. Od 2008 do 2020 działała jako Kozminski Erasmus Student Network. Wspiera nowo przybyłych studentów w sprawach studiów, zakwaterowania i integracji kulturowej.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/KIS%20logo.png",
            "supervisor": None,
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/kis_kozminski_society/",
            "facebook_url": "https://www.facebook.com/KUInternationalSociety",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/kozminski-international-society/",
        },
        {
            "name": "Studencka Poradnia Prawna",
            "login": "poradnia_prawna",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Organizacje Studenckie",
            "description": "Umożliwia naukę prawa poprzez jego praktykowanie. Poradnia zapewnia bezpłatną pomoc prawną w sześciu obszarach: prawo karne, administracyjne, rodzinne, pracy, cywilne oraz handlowe/konsumenckie. 1. miejsce w Rankingu Wydziałów Prawa Rzeczpospolitej 2023.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/poradnia%20prawna%20logo.png.png",
            "supervisor": "Dr Mateusz Woiński",
            "email": "[email protected]",
            "instagram_url": None,
            "facebook_url": "https://www.facebook.com/SPPALK",
            "website_url": "https://www.kozminski.edu.pl/pl/studencka-poradnia-prawna-dla-klientow",
            "linkedin_url": None,
        },
        {
            "name": "Green Kozminski",
            "login": "green_kozminski",
            "password": placeholder_pwd,
            "role": "club",
            "type": "club",
            "category": "Organizacje Studenckie",
            "description": "Organizacja studencka działająca przy Centrum Zrównoważonego Rozwoju, skupiająca się na działalności w obszarze zrównoważonego rozwoju i odpowiedzialności biznesu. Pracuje na rzecz realizacji Celów Zrównoważonego Rozwoju ONZ.",
            "logo_url": "https://www.kozminski.edu.pl/sites/leon/files/images/green%20kozminski%20logo.jpg",
            "supervisor": None,
            "email": "[email protected]",
            "instagram_url": "https://www.instagram.com/green.kozminski/",
            "facebook_url": "https://www.facebook.com/greenkozminski/",
            "website_url": None,
            "linkedin_url": "https://www.linkedin.com/company/greenkozminski/",
        },
    ]

    op.bulk_insert(clubs_table, clubs)


def downgrade() -> None:
    # Remove seeded clubs (by login, since those are unique)
    op.execute(
        "DELETE FROM clubs WHERE login IN ("
        "'women_in_org','kozminski_business_club','kolo_sukces','skn_psychonomia',"
        "'nextgen_pm','culture_club','skn_tiger','kozminski_ai','skn_kreatywni',"
        "'skn_fmc','dsb_kozminski','skn_audytor','kcc_kozminski','kolo_bankowe',"
        "'skn_kapitalni','pro_libertate','lex_medicinae','crimen_et_poena',"
        "'societas_sportivi','actio_efficiens','kozminski_energy','skn_ex_ante',"
        "'ius_mercatorum','skn_forum','skn_unitas','kis_kozminski',"
        "'poradnia_prawna','green_kozminski'"
        ")"
    )
    op.drop_column("clubs", "category")
    op.drop_column("clubs", "supervisor")
    op.drop_column("clubs", "linkedin_url")
